// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWpulCpgGONGgf4mDT3bN---v5wZyApX4',
    appId: '1:309426946323:web:b1051e4a25350607505ae6',
    messagingSenderId: '309426946323',
    projectId: 'flutgo',
    authDomain: 'flutgo.firebaseapp.com',
    databaseURL: 'https://flutgo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutgo.appspot.com',
    measurementId: 'G-RT9R6JRC1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgE8h8AFnLxSTMWS_oO-V33rSYqA7ilI',
    appId: '1:309426946323:android:2c4a22f1ac922539505ae6',
    messagingSenderId: '309426946323',
    projectId: 'flutgo',
    databaseURL: 'https://flutgo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJdYeBotvEHO98C1rXEuOBv_yi_j2p9E',
    appId: '1:309426946323:ios:089b39caf27176d0505ae6',
    messagingSenderId: '309426946323',
    projectId: 'flutgo',
    databaseURL: 'https://flutgo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutgo.appspot.com',
    iosClientId: '309426946323-3qeuvc2csutpo4vp0mkqc1i15p6p01a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBgIsolates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJdYeBotvEHO98C1rXEuOBv_yi_j2p9E',
    appId: '1:309426946323:ios:089b39caf27176d0505ae6',
    messagingSenderId: '309426946323',
    projectId: 'flutgo',
    databaseURL: 'https://flutgo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutgo.appspot.com',
    iosClientId: '309426946323-3qeuvc2csutpo4vp0mkqc1i15p6p01a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBgIsolates',
  );
}
